Add most populars
svlgerasimov/java-filmorate pull request #10
Opened 2022-11-08 12:50 UTC by lyrapanged

2022-11-08 17:16 UTC, Sofi2022 approved these changes
На мой взгляд все окей

2022-11-08 17:47 UTC, BarkovRoman approved these changes

2022-11-08 18:51 UTC, svlgerasimov requested changes

2022-11-08 18:51 UTC, svlgerasimov commented on src/test/java/ru/yandex/practicum/filmorate/storage/db/LikesDbStorageTest.java
> -    @Test
Почему бы просто не поменять в тесте сигнатуру метода getMostPopularFilms на новую, просто без фильтрации по году и жанру? Т.е. изменится только getMostPopularFilms(count, null, null)

2022-11-08 18:51 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +    private List<Film> getMostPopularFilmsByCount(int count) {
Я бы предложил определиться в какой тип у count. Здесь int, а в аналогичных методах выше Integer. В принципе этот параметр всегда есть, поэтому в этом классе и выше по цепочке вызовов я бы вернул int

2022-11-08 18:51 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +    private List<Film> getMostPopularFilmsByCountAndGenreAndYear(Integer count, Long genreId, Integer year) {
Как предложение было бы крутое решение с одним методом вместо четырёх (в слаке уже немного это обсуждали)

2022-11-08 20:22 UTC, lyrapanged commented on src/test/java/ru/yandex/practicum/filmorate/storage/db/LikesDbStorageTest.java
> -    @Test
Изначально, я заменил на верную сигнатуру  т.к использовал для genreID  и year примитивные типы c дефолтным значением -1, а поменяв  на оболочку, забыл изменить тест. Говорили, что тесты не нужны и я бездумно закоментил его) Исправил.

2022-11-08 20:23 UTC, lyrapanged commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +    private List<Film> getMostPopularFilmsByCountAndGenreAndYear(Integer count, Long genreId, Integer year) {
+

2022-11-09 12:33 UTC, TerentevOleg approved these changes

2022-11-10 10:30 UTC, svlgerasimov approved these changes

2022-11-10 10:59 UTC, merged