Add remove endpoint
svlgerasimov/java-filmorate pull request #12
Opened 2022-11-08 13:06 UTC by lyrapanged

2022-11-08 13:38 UTC, svlgerasimov requested changes

2022-11-08 13:38 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final LikesStorage likesStorage;
LikesStorage разве здесь используется?

2022-11-08 13:38 UTC, svlgerasimov commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS film, users, film_genre, genre, mpa, likes, friends, reviews, like_review, dislike_review, events;
Согласен, это забыли)

2022-11-08 16:38 UTC, TerentevOleg approved these changes

2022-11-08 20:35 UTC, lyrapanged commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final LikesStorage likesStorage;
Остатки былой роскоши. Удалил.

2022-11-08 20:57 UTC, TerentevOleg approved these changes

2022-11-09 03:46 UTC, svlgerasimov approved these changes

2022-11-09 03:46 UTC, merged