Add director
svlgerasimov/java-filmorate pull request #13
Opened 2022-11-09 17:41 UTC by Sofi2022

Ветка add-director для командного ревью

2022-11-10 07:20 UTC, BarkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    String name;
Поля должны быть приватными. Так же лучше использовать аннотация @Value, она сгенерирует геттеры,  поля private final и конструктор.

2022-11-10 07:20 UTC, BarkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +    private final Logger log = LoggerFactory.getLogger(DirectorDbStorage.class);
Для логирования удобней использовать аннотацию @Slf4j.

2022-11-10 07:20 UTC, BarkovRoman commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +    private final FilmDbStorage filmDbStorage;
Если поле не используется, то его лучше удалить.

2022-11-10 08:22 UTC, svlgerasimov requested changes

2022-11-10 08:22 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    private final DirectorDbStorage directorDbStorage;
Хорошо бы выделить для режиссёров слой сервисов (новый класс DirectorService). Там будут методы, которые будут обращаться к DAO (т.е. DirectorStorage). А в контроллере уже вызываются методы DirectorService. Это касается всех методов контроллера.

2022-11-10 08:22 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public Optional<Director> updateDirector(@RequestBody Director director) {
Кажется здесь не хватает аннотации Valid

2022-11-10 08:22 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        String sql = "SELECT f.id, f.name, f.description, f.release_date, f.duration, d.director_id, " +
Т.к. список режиссёров добавляется на другом уровне (режиссёры добавляются в сервисе), здесь нет необходимости добавлять в запрос поля и джойнить таблицы, связанные с режиссёрами

2022-11-10 08:22 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +    public Optional<Film> getById(long id) { // добавить директора
Т.к. список режиссёров добавляется на другом уровне, здесь нет необходимости добавлять в запрос поля и джойнить таблицы, связанные с режиссёрами

2022-11-10 08:22 UTC, svlgerasimov commented on src/main/resources/schema.sql
> +    DIRECTOR_ID BIGINT auto_increment PRIMARY KEY,-- references film_directors(director_id),
Так тоже работает, но предлагаю, чтобы не путаться, во всех таблицах формировать первичный ключ одинаково, т.е. GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY

2022-11-10 13:29 UTC, svlgerasimov requested changes

2022-11-10 13:29 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final Logger log = LoggerFactory.getLogger(FilmController.class);
К проекту подключен logbook, который логгирует http-запросы. Дополнительно логгировать запросы нет особого смысла

2022-11-10 13:29 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.debug("Dir: {}", film.getDirectors());
В первой строчке логгирования уже есть информация о режиссёрах. Дополнительно писать в лог список режиссёров незачем

2022-11-10 13:29 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +    private final FilmDbStorage filmDbStorage;
Бины лучше объявлять через интерфейс, т.е. FilmStorage, а не FilmDbStorage

2022-11-10 13:29 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/inmemory/FilmDirectorsStorage.java
> +package ru.yandex.practicum.filmorate.storage.inmemory;
Интерфейс лучше вынести из пакета inmemory в ru.yandex.practicum.filmorate.storage, где и лежат остальные интерфейсы хранилищ

2022-11-10 19:00 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> findByDirector(@PathVariable long directorId, @RequestParam FilmSortBy sortBy) {
Значения в FilmSortBy, как и в любом другом enum, должны быть все заглавными буквами. Кодстайл нас к этому обязывает. Чтобы избежать здесь проблем с десериализацией можно сделать так:
в аргументе поменять тип на String, а дальше сделать
filmService.findByDirector(directorId, **FilmSortBy.valueOf(sortBy.toUpperCase())**)

2022-11-10 19:12 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +        String directorsSql = "select * from director";
В запросах вместо * лучше всё-таки перечислять названия полей. Так проще разобраться, если что-то пойдёт не так с маппером

2022-11-10 19:14 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +            throw new NotFoundException("Такого режиссера нет");
Здесь лучше вернуть пустой Optional (т.е. Optional.empty()), а исключение уже выбросить в сервисе, когда пришёл пустой Optional

2022-11-10 19:15 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +        log.info("вызван метод");
Такие записи в лог возможно полезны при отладке, но из итогового кода их лучше убрать )

2022-11-10 19:17 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +        checkDirectorExists(director.getId());
Проверку наличия режиссёра с нужным id лучше, как и другие такие проверки перенести в сервис

2022-11-10 19:20 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDirectorsDbStorage.java
> +    public List<Film> findByDirector(long directorId, FilmSortBy sortBy) {
По-моему по функционалу логичнее было бы перенести этот метод в FilmService

2022-11-10 19:28 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDirectorsDbStorage.java
> +
Мне кажется, логичнее перенести метод с запросом sql в FilmDbStorage.
Также логично по аналогии с другими методами, которые достают из базы фильмы в этом методе возвращать фильмы без жанров и режиссёров, а добавлять эти списки после вызова метода в findByDirector.

2022-11-10 19:33 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDirectorsDbStorage.java
> +                "LEFT JOIN film_genre AS fg ON f.id = fg.film_id " +
Джойнить жанры нет особого смысла, т.к. список жанров прицепляется после выполнения запроса. То же самое касается режиссёров. Достаточно присоединить film_directors, чтобы использовать из этой таблицы director_id в where.
И не совсем понятно зачем может быть нужна группировка по director_id

2022-11-10 19:38 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDirectorsDbStorage.java
> +        Map<Long, List<Director>> directors = getAllFilmDirectors();
Доставать из базы мапу со списками режиссёров всех-всех фильмов, чтобы выбрать оттуда только нужные фильмы, может быть слишком "дорого". Было бы круто сделать в FilmDirectorsStorage методы getDirectorsByFilmIds(Collection<Long> filmIds), который достаёт из базы списки режиссёров только нужных фильмов. И здесь вызвать именно этот метод, потому что нам нужна мапа не с режиссёрами всех фильмов, а только фильмов, которые есть в списке films.
Аналогичный метод есть в FilmGenresStorage. Если будет нужна помощь с sql запросом - обязательно помогу.

2022-11-11 07:22 UTC, svlgerasimov requested changes

2022-11-11 07:22 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +    public static Film makeFilm(ResultSet resultSet) throws SQLException {
Когда метод поиска фильмов по режиссёру переедет в этот класс, makeFilm можно будет вернуть модификатор private

2022-11-11 21:26 UTC, svlgerasimov requested changes

2022-11-11 21:26 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +        directorService.getDirectorById(director.getId());
Проверка на наличие режиссёра уже есть в сервисе. Здесь дублировать запрос к базе не обязательно

2022-11-11 21:26 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +        directorService.getDirectorById(id);
Проверка на наличие режиссёра уже есть в сервисе. Здесь дублировать запрос к базе не обязательно

2022-11-11 21:26 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +                "WHERE fd.director_id = ? GROUP BY f.id, fd.director_id";
Группировка по director_id точно нужна? Возможно достаточно будет группировки только по фильму?

2022-11-13 13:43 UTC, svlgerasimov approved these changes

2022-11-13 13:55 UTC, lyrapanged approved these changes

2022-11-13 14:04 UTC, merged