add common films
svlgerasimov/java-filmorate pull request #8
Opened 2022-11-07 13:02 UTC by TerentevOleg

2022-11-08 08:43 UTC, svlgerasimov requested changes

2022-11-08 08:43 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        String sql =
Есть пара предложений как улучшить читаемость запроса. Это именно предложение, работает вроде всё и так, так что здесь точно возможна дискуссия )
Подзапрос с поиском общих айдишников фильмов для двух пользователей я бы выделил в CTE (https://antonz.ru/cte/) и, возможно заменил бы в нём 2 подзапроса с INTERSECT на один запрос с джойном таблицы лайков к самой себе (но про это не уверен, что это лучше).
Тогда можно будет работать с таблицей айдишников общих фильмов просто как с ещё одной таблицей, и всё можно будет засунуть в один select.
Т.е. получится примерно следующее:
WITH common_films AS (SELECT ...-запрос для id общих фильмов )
SELECT f.id, f.name, ...., cf.film_id 
FROM common_films AS cf
JOIN film AS f ON ...
...

И ещё вместо * по-моему лучше перечислять поля. Так проще не запутаться, если с маппером что-то пойдёт не так.

2022-11-08 08:43 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Map<Long, List<Genre>> genres = filmGenreStorage.getAllFilmGenres();
Может быть есть смысл дополнительно проверить, есть ли пользователи с userId и friendId, и если кого-то нет, выдать 404?
Если конечно это не идёт в разрез с постманом (я не смотрел)

2022-11-08 09:24 UTC, TerentevOleg commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Map<Long, List<Genre>> genres = filmGenreStorage.getAllFilmGenres();
Добавил проверку checkUserExists

2022-11-08 09:25 UTC, TerentevOleg commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.debug("Film service: common films for users id={} and friend id={}", userId, friendId);
Согласен, в этом нет необходимости)

2022-11-10 22:23 UTC, TerentevOleg commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        String sql =
Перечислил поля, переписать запрос красивее у меня не получается. Если использовать CTE, то все равно получается длинная тряпка, не вижу смысла в нем в таком случае.

2022-11-11 06:15 UTC, svlgerasimov approved these changes

2022-11-11 10:40 UTC, BarkovRoman approved these changes

2022-11-11 12:01 UTC, merged