Add feed
svlgerasimov/java-filmorate pull request #9
Opened 2022-11-07 14:30 UTC by TerentevOleg

2022-11-07 16:11 UTC, BarkovRoman approved these changes

2022-11-08 09:06 UTC, svlgerasimov requested changes

2022-11-08 09:06 UTC, svlgerasimov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        eventStorage.addEvent(userId, EventType.FRIEND, EventOperation.ADD, friendId);
Мне кажется, немного удобнее было бы сделать EventService и пользоваться им для добавления в историю. Заодно логгирование можно запихнуть туда.
Кстати насчёт логгирования. Я бы предложил просто писать в лог toString от того, что вернёт база после добавления события.

2022-11-08 10:44 UTC, TerentevOleg commented on src/main/resources/schema.sql
> +    entity_id  BIGINT
Исправлено. NULL быть не может

2022-11-08 11:52 UTC, svlgerasimov approved these changes

2022-11-08 11:53 UTC, merged